name: Sync labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: strangerstudios/label-sync@v2
        with:
          source-repo: strangerstudios/paid-memberships-pro
          delete-other-labels: true
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
